### ISSUE TITLE
Exit jay

### ISSUE THREAD

**Issue by samjeffress** [nikersify/jay#15]
Hi, 

I'm loving `jay`, but have only just figured out how to exit via `process.exit()`. 

In my node repl it will respond to:
* Ctrl + C
* `exit()`

It'd be sweet if jay could do this too. I'm happy to have a look at making this work if you think it'd be accepted.

Sam

**Comment by nikersify** [comment]
hey, when in the repl you can press `ctrl+d` at any time in order to exit. hope that helps.

**Comment by samjeffress** [comment]
👍 thanks, that works a charm
