### ISSUE TITLE
Command history persistence

### ISSUE THREAD

**Issue by schfkt** [nikersify/jay#5]
Hi. 
Does it store command history in a file anywhere? Node.js REPL, for example, saves the commands in a file at `~/.node_repl_history` and loads it on the next invocation of a REPL, so you get a persistent history of the commands entered.

**Comment by nikersify** [comment]
Hey, Jay doesn't persist any command history at the moment, the feature is on the "roadmap" though 🙂

**Comment by nikersify** [comment]
shipped in 0.2.0 :tada:

**Comment by schfkt** [comment]
@nikersify nice. Thanks!
