### ISSUE TITLE
autocomplete new definitions just typed

### ISSUE THREAD

**Issue by laoshaw** [nikersify/jay#9]
jay looks promising, normally we will create new variables etc under jay but jay seems ignore them for autocomplete, it will be nice is jay can remember any new definitions in current session and provide autocomplete for them on the go, so I don't need retype "superlongvariable" after the first time I did "let superlongvarible", instead jay will help to autocomplete it

**Comment by nikersify** [comment]
I did some work on the `global-lexical-scope-names` branch in this repo but I'm not sure it's 100% stable yet, would you mind checking it out @laoshaw ? Building instructions are on the bottom of the readme.

**Comment by laoshaw** [comment]
I did 'npm run build' and after that how to run jay?  how to build and run is unclear to me still

**Comment by nikersify** [comment]
![image](https://user-images.githubusercontent.com/7091471/62010201-f879f200-b167-11e9-8f47-8a0fb820dba6.png)

**Comment by laoshaw** [comment]
works well in my case, tried both variable names and functions names, can keep autocomplete for xzy123,xyz1233, xyz12333 with TAB key

**Comment by nikersify** [comment]
nice, thanks for reporting & testing :)
